sudo: false
bundler_args: "--standalone --binstubs --without development"
cache: bundler
script: script/test_all
before_script:
  - mysql -e 'create database will_paginate;'
  - psql -c 'create database will_paginate;' -U postgres
rvm:
  - 1.8.7
  - 1.9.3
  - 2.1.8
  - 2.2.4
  - 2.3.0
gemfile:
  - Gemfile
  - Gemfile.rails3.0
  - Gemfile.rails3.1
  - Gemfile.rails3.2
  - Gemfile.rails4.1
  - Gemfile.rails4.2
matrix:
  exclude:
    - rvm: 1.8.7
      gemfile: Gemfile
    - rvm: 1.8.7
      gemfile: Gemfile.rails4.1
    - rvm: 1.8.7
      gemfile: Gemfile.rails4.2
